<footer id="rodape">
  <table>

    <thead>
      <tr>
        <td><span>Índice</span></td>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><a href="index.php">Início</a></td>
      </tr>

      <tr>
        <td><a href="../servicos_andamento.php">Serviços em andamento</a></td>
      </tr>

      <tr>
        <td><a href="../Utilitarios/encerrar_sessao.php">Sair</a></td>
      </tr>

      <tr>
        <td>
          <p> © 2023 - Todos os direitos reservados</p>
        </td>    
      </tr>
    </tbody>

  </table>
  
</footer>