<footer id="rodape">
  <table>

    <thead>
      <tr>
        <td><span>Índice</span></td>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><a href="../index.php">Início</a></td>
      </tr>

      <tr>
        <td><a href="../sobre.php">Sobre nós</a></td>
      </tr>

      <tr>
        <td><a href="../login.php">Entrar</a></td>
      </tr>

      <tr>
        <td>
          <p> &copy 2023 - Todos os direitos reservados</p>
        </td>    
      </tr>
    </tbody>

  </table>
  
</footer>